//-- browser name constants

var BROWSER_NAME_IE = 'Internet Explorer'
    , BROWSER_NAME_FF = 'Firefox'
    , BROWSER_NAME_CHROME = 'Chrome'
    , BROWSER_NAME_SAFARI = 'Safari';

// -- reg exp

var INTERSTITIAL_PAGE_REG_EXP = /^https?:\/\/letyshops\.ru\/view\//i;
var EXTENSION_OWNER_PAGE = 'letyshops\.ru';
var PARAMETER_DEEP_LINK = "?ext_referrer=";

//-- events

var COMMUNICATION_EVENT_NAME_PREFIX = 'LETYSHOPS_',

    LOGIN_TOKEN = COMMUNICATION_EVENT_NAME_PREFIX + 'LOGIN_TOKEN',
    POPUP_FIRST_OPENING_TOKEN = COMMUNICATION_EVENT_NAME_PREFIX + 'POPUP_FIRST_OPENING_TOKEN',

    CASHBACK_ACTIVATE = COMMUNICATION_EVENT_NAME_PREFIX + 'CASHBACK_ACTIVATE',
    CASHBACK_DEACTIVATE = COMMUNICATION_EVENT_NAME_PREFIX + 'CASHBACK_DEACTIVATE',
    CASHBACK_ACTIVATE_FROM_POPUP = COMMUNICATION_EVENT_NAME_PREFIX + 'CASHBACK_ACTIVATE_FROM_POPUP',
    PROMO_ACTIVATE = COMMUNICATION_EVENT_NAME_PREFIX + 'PROMO_ACTIVATE',
    PROMO = COMMUNICATION_EVENT_NAME_PREFIX + 'PROMO',

    NOTIFICATION_CASHBACK_ACTIVATE = COMMUNICATION_EVENT_NAME_PREFIX + 'NOTIFICATION_CASHBACK_ACTIVATE',
    NOTIFICATION_DISMISS = COMMUNICATION_EVENT_NAME_PREFIX + 'NOTIFICATION_DISMISS',
    USER_NOTIFICATION_DISMISS = COMMUNICATION_EVENT_NAME_PREFIX + 'USER_NOTIFICATION_DISMISS',
    NOTIFICATION_GET_INFO = COMMUNICATION_EVENT_NAME_PREFIX + 'NOTIFICATION_GET_INFO',
    SHOW_NOTIFICATION_BY_FORCE = COMMUNICATION_EVENT_NAME_PREFIX + 'SHOW_NOTIFICATION_BY_FORCE',
    CLOSE_ALL_NOTIFICATION = COMMUNICATION_EVENT_NAME_PREFIX + 'CLOSE_ALL_NOTIFICATION',
    USER_NOTIFY_GET_INFO = COMMUNICATION_EVENT_NAME_PREFIX + 'USER_NOTIFY_GET_INFO',
    UPDATE_FAVORITE_STATUS_FROM_NOTIFICATION = COMMUNICATION_EVENT_NAME_PREFIX + 'UPDATE_FAVORITE_STATUS_FROM_NOTIFICATION',
    UPDATE_FAVORITE_STATUS_FROM_BG = COMMUNICATION_EVENT_NAME_PREFIX + 'UPDATE_FAVORITE_STATUS_FROM_NOTIFICATION',

    GET_EXTENSION_INFO = COMMUNICATION_EVENT_NAME_PREFIX + 'GET_EXTENSION_INFO',
    SEND_EXTENSION_INFO = COMMUNICATION_EVENT_NAME_PREFIX + 'SEND_EXTENSION_INFO',
    GET_PAGE_INFO = COMMUNICATION_EVENT_NAME_PREFIX + 'GET_PAGE_INFO',
    SEND_GA_CID = COMMUNICATION_EVENT_NAME_PREFIX + 'SEND_GA_CID',
    SEND_GOOGLE_ANALYTICS = COMMUNICATION_EVENT_NAME_PREFIX + 'SEND_GOOGLE_ANALYTICS',
    SEND_ACTIVATION_DATA = COMMUNICATION_EVENT_NAME_PREFIX + 'SEND_ACTIVATION_DATA',
    SEND_PAGE_INFO = COMMUNICATION_EVENT_NAME_PREFIX + 'SEND_PAGE_INFO',
    ANIMATE_ICON = COMMUNICATION_EVENT_NAME_PREFIX + 'ANIMATE_ICON',
    OFFLINE_LIKES = COMMUNICATION_EVENT_NAME_PREFIX + 'OFFLINE_LIKES',
    SAW_REWRITE = COMMUNICATION_EVENT_NAME_PREFIX + 'SAW_REWRITE',
    SAVE_PARAMS = COMMUNICATION_EVENT_NAME_PREFIX + 'SAVE_PARAMS',
    BUTTON_UPDATE = COMMUNICATION_EVENT_NAME_PREFIX + 'BUTTON_RED',
    SET_NOTIFICATIONS_POPUP = COMMUNICATION_EVENT_NAME_PREFIX + 'SET_NOTIFICATIONS_POPUP',
    TAB_WAS_CHANGED = COMMUNICATION_EVENT_NAME_PREFIX + 'TAB_WAS_CHANGED',

// check cookies
    CHECK_MERCHANT_COOKIES = COMMUNICATION_EVENT_NAME_PREFIX + 'CHECK_MERCHANT_COOKIES',
    SET_MERCHANT_COOKIES = COMMUNICATION_EVENT_NAME_PREFIX + 'SET_MERCHANT_COOKIES',
    CLEAR_COOKIES = COMMUNICATION_EVENT_NAME_PREFIX + 'CLEAR_COOKIES',

    MERCHANT_SUPPRESSED = COMMUNICATION_EVENT_NAME_PREFIX + 'MERCHANT_SUPPRESSED',
    MERCHANTS_RESET = COMMUNICATION_EVENT_NAME_PREFIX + 'MERCHANTS_RESET',

    POPUP_MERCHANTS_UPDATE = COMMUNICATION_EVENT_NAME_PREFIX + 'POPUP_MERCHANTS_UPDATE',
    POPUP_TO_NOTIFICATION_TAB = COMMUNICATION_EVENT_NAME_PREFIX + 'POPUP_TO_NOTIFICATION_TAB',
    POPUP_TO_INVITATION_TAB = COMMUNICATION_EVENT_NAME_PREFIX + 'POPUP_TO_INVITATION_TAB',
    POPUP_TO_MERCHANT_CARD = COMMUNICATION_EVENT_NAME_PREFIX + 'POPUP_TO_MERCHANT_CARD',
    POPUP_INITIALIZE_FOOTER_FOR_OFFERS = COMMUNICATION_EVENT_NAME_PREFIX + 'POPUP_INITIALIZE_FOOTER_FOR_OFFERS',
    POPUP_INITIALIZE_FOOTER_FOR_STORES = COMMUNICATION_EVENT_NAME_PREFIX + 'POPUP_INITIALIZE_FOOTER_FOR_STORES',
    POPUP_UPDATE_FOOTER = COMMUNICATION_EVENT_NAME_PREFIX + 'POPUP_UPDATE_FOOTER',
    POPUP_TO_UPDATE_FAVORITE_STATUS = COMMUNICATION_EVENT_NAME_PREFIX + 'POPUP_TO_UPDATE_FAVORITE_STATUS',
    POPUP_PUSH_REVIEWED_NOTIFY = COMMUNICATION_EVENT_NAME_PREFIX + 'POPUP_PUSH_REVIEWED_NOTIFY',
    ON_USER_LOGIN = COMMUNICATION_EVENT_NAME_PREFIX + 'ON_USER_LOGIN',
    ON_USER_LOGOUT = COMMUNICATION_EVENT_NAME_PREFIX + 'ON_USER_LOGOUT',
    USER_FETCH_INFO = COMMUNICATION_EVENT_NAME_PREFIX + 'USER_FETCH_INFO';


var TAB_CHANGED = COMMUNICATION_EVENT_NAME_PREFIX + 'TAB_CHANGED'
    , TAB_SET_MERCHANT_ALIAS_AND_DEEP_LINK = COMMUNICATION_EVENT_NAME_PREFIX + 'TAB_SET_MERCHANT_ALIAS_AND_DEEP_LINK'
    , NOTIFICATION_ACTIVATED_DISMISS = COMMUNICATION_EVENT_NAME_PREFIX + 'NOTIFICATION_ACTIVATED_DISMISS'
    , CASHBACK_ACTIVATE_AFTER_LOG_IN = COMMUNICATION_EVENT_NAME_PREFIX + 'CASHBACK_ACTIVATE_AFTER_LOG_IN'
    , MERCHANT_GET_INFO = COMMUNICATION_EVENT_NAME_PREFIX + 'MERCHANT_GET_INFO'
    , CHECK_BUTTON_INDICATION = COMMUNICATION_EVENT_NAME_PREFIX + 'CHECK_BUTTON_INDICATION';

//-- SIZE OF USER HISTORY

var HISIORY_LENGTH = 10,
    GLOBAL_HISTORY_LENGTH = 100;

//-- UI

var POPUP_WIDTH = 470
    , POPUP_HEIGHT = 560;

// UPDATE_INTERVALS

var UPDATE_INTERVAL_MERCHANT = 7 * 60 * 60 * 1000, // 7h
    UPDATE_INTERVAL_OFFERS = 4 * 60 * 60 * 1000, // 4h
    UPDATE_INTERVAL_CODES = 60 * 60 * 1000, // 1h
    UPDATE_INTERVAL_USER_AFTER_ERROR = 30 * 1000, //30s
    REQUESTS_PERIOD_IN_CASE_OF_ERROR = 1 * 60 * 1000, //1m
    PERIODIC_SHOP_VIEWED = 2 * 60 * 60 * 1000, //2h
    USER_NOTIFY_INTERVAL = 5 * 1000, //5s
    UPDATE_INTERVAL_ACTIVATE = 1 * 60 * 60 * 1000,// 1h
    UPDATE_INTERVAL_USER = 1 * 60 * 1000, //1 m
    UPDATE_INTERVAL_USER_NOTIFICATION = 60 * 60 * 1000, // 5 m
    UPDATE_INTERVAL_FAVORITE = 2 * 60 * 60 * 1000, // 2h
    UPDATE_INTERVAL_RECOMMENDED = 5 * 60 * 1000, // 3 m
    UPDATE_INTERVAL_VIEWED = 1 * 60 * 1000, // 1 m
    UPDATE_READING_LABEL = 5000; // 5s

//-- tab possible states

var TAB_STATE_3RD_PARTY = 0x02
    , TAB_STATE_INTERSTITIAL_REDIRECT = 0x03;

// footer state
var FOOTER_ALL_STORES = 0x01,
    FOOTER_ALL_OFFERS = 0x02,
    FOOTER_LABEL = 0;

//-- list of 3rd party affiliate links domains

var THIRD_PARTY_LINKS = [
    'event.2parale.ro',
    'www.awin1.com',
    'partners.webmasterplan.com',
    'web.epartner.es',
    'clic.reussissonsensemble.fr',
    'being.successfultogether.co.uk',
    'anrdoezrs.net',
    't.dgm-au.com',
    'google.com/aclk?sa',
    'pepperjamnetwork.com',
    'aos.prf.hn',
    'ad.zanox.com',
    'rover.ebay.com',
    'track.commissionfactory.com.au',
    'clk.tradedoubler.com',
    'tkqlhce.com',
    'partnerprogramma.bol.com',
    'tc.tradetracker.net',
    'tr.rdrtr.com',
    'lead-analytics.nl',
    'partners.adtriplex.com',
    'action.metaffiliation.com',
    'smart4ads.com',
    'gr.linkwi.se',
    'tracking.publicidees.com',
    'fls.doubleclick.net',
    'gan.doubleclick.net',
    'click.linksynergy.com',
    'v2.afilio.com.br',
    'jdoqocy.com',
    'send.onenetworkdirect.net',
    '.7eer.net',
    '.evyy.net',
    '.ojrq.net',
    'affiliate.buy.com',
    'affiliate.rakuten.com',
    'affiliates.abebooks.com',
    'affiliates.babiesrus.com',
    'affiliates.toysrus.com',
    'afsrc=1',
    'aos.prf.hn',
    'commission-junction.com',
    'dpbolvw.net',
    'dpbolvw.net',
    'google.com/aclk',
    'gopjn.com',
    'goto.orientaltrading.com',
    'goto.target.com',
    'goto.target.com/c/',
    'kqzyfj.com',
    'partners.hotwire.com',
    'pepperjamnetwork.com',
    'pjatr.com',
    'pjtra.com',
    'pntra.com',
    'pntrs.com',
    'prf.hn',
    'qksrv.net',
    'shareasale.com',
    't.dgm-au.com',
    'www.linkconnector.com'
];

var defaultCausebase64 = 'data:image/png;base64,';

//-- google analytics
var googleAnalyticsTID = 'UA-179316-11',
    googleAnalyticsURL = 'https://www.google-analytics.com',
    googleAnalyticsURLBatch = googleAnalyticsURL + '/batch',
    googleAnalyticsURLCollect = googleAnalyticsURL + '/collect',
    gaPrefix = '/_extension/',
    gaPageShops = gaPrefix + 'shops/',
    gaPagePopup = gaPrefix + 'popup/',
    gaPageSales = gaPrefix + 'sales/',
    gaPageFriends = gaPrefix + 'friends/',
    gaPageHistory = gaPrefix + 'history/',
    gaPageError = gaPrefix + '404/';



